### ISSUE TITLE
Flagged as proprietary on flathub

### ISSUE THREAD

**Issue by 1bcb** [flathub/org.kde.kollision#26]
The Flathub page says that Kollision has proprietary code.  I'm guessing this is a mistake.

**Comment by travier** [comment]
The project license is missing in https://invent.kde.org/games/kollision/-/blob/master/src/org.kde.kollision.appdata.xml?ref_type=heads. Example: https://invent.kde.org/games/bomber/-/blob/master/src/org.kde.bomber.appdata.xml?ref_type=heads#L5

**Comment by travier** [comment]
https://invent.kde.org/games/kollision/-/merge_requests/14

**Comment by travier** [comment]
Thanks for the report. This will be fixed in the next release as the PR above has been merged. Closing.
